apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness-app # This must match the template label below
  template:
    metadata:
      labels:
        app: aceest-fitness-app
    spec:
      containers:
      - name: aceest-fitness-container # This name is required by kubectl set image
        image: surajgundla/aceest-fitness:latest # This will be updated by the pipeline
        ports:
        - containerPort: 8080 # Example port for a web app
