apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-app-svc
spec:
  type: NodePort
  selector:
    app: aceest-fitness-app
    color: blue # Initially, point to the blue deployment
  ports:
  - port: 80
    targetPort: 8080
